import "./globals.css";
import { Header } from "@/ui";
export const metadata = {
  title: "Daveloper",
  description: "Generated by create next app",
};

const headerItems = [
  { label: "Inicio", href: "/" },
  { label: "Blog", href: "/blog" },
];

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        style={{ display: "flex", flexDirection: "column", minHeight: "100vh" }}
      >
        <Header items={headerItems} />
        <main style={{ flex: 1 }}>{children}</main>
      </body>
    </html>
  );
}
